// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpaceShip.proto

package com.example.demo.api;

public final class SpacShipProtos {
  private SpacShipProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SpaceShipOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.example.demo.api.SpaceShip)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string model = 1;</code>
     */
    String getModel();
    /**
     * <code>optional string model = 1;</code>
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>optional string captain = 2;</code>
     */
    String getCaptain();
    /**
     * <code>optional string captain = 2;</code>
     */
    com.google.protobuf.ByteString
        getCaptainBytes();

    /**
     * <code>optional int32 fuel = 3;</code>
     */
    int getFuel();

    /**
     * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
     */
    int getCargoValue();
    /**
     * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
     */
    SpaceShip.CargoType getCargo();
  }
  /**
   * Protobuf type {@code com.example.demo.api.SpaceShip}
   */
  public  static final class SpaceShip extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.example.demo.api.SpaceShip)
      SpaceShipOrBuilder {
    // Use SpaceShip.newBuilder() to construct.
    private SpaceShip(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpaceShip() {
      model_ = "";
      captain_ = "";
      fuel_ = 0;
      cargo_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SpaceShip(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              model_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              captain_ = s;
              break;
            }
            case 24: {

              fuel_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              cargo_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SpacShipProtos.internal_static_com_example_demo_api_SpaceShip_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SpacShipProtos.internal_static_com_example_demo_api_SpaceShip_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpaceShip.class, Builder.class);
    }

    /**
     * Protobuf enum {@code com.example.demo.api.SpaceShip.CargoType}
     */
    public enum CargoType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FRUIT = 0;</code>
       */
      FRUIT(0),
      /**
       * <code>WEAPONS = 1;</code>
       */
      WEAPONS(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FRUIT = 0;</code>
       */
      public static final int FRUIT_VALUE = 0;
      /**
       * <code>WEAPONS = 1;</code>
       */
      public static final int WEAPONS_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static CargoType valueOf(int value) {
        return forNumber(value);
      }

      public static CargoType forNumber(int value) {
        switch (value) {
          case 0: return FRUIT;
          case 1: return WEAPONS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<CargoType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          CargoType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<CargoType>() {
              public CargoType findValueByNumber(int number) {
                return CargoType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return SpaceShip.getDescriptor().getEnumTypes().get(0);
      }

      private static final CargoType[] VALUES = values();

      public static CargoType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private CargoType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.example.demo.api.SpaceShip.CargoType)
    }

    public static final int MODEL_FIELD_NUMBER = 1;
    private volatile Object model_;
    /**
     * <code>optional string model = 1;</code>
     */
    public String getModel() {
      Object ref = model_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        model_ = s;
        return s;
      }
    }
    /**
     * <code>optional string model = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPTAIN_FIELD_NUMBER = 2;
    private volatile Object captain_;
    /**
     * <code>optional string captain = 2;</code>
     */
    public String getCaptain() {
      Object ref = captain_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        captain_ = s;
        return s;
      }
    }
    /**
     * <code>optional string captain = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCaptainBytes() {
      Object ref = captain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        captain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUEL_FIELD_NUMBER = 3;
    private int fuel_;
    /**
     * <code>optional int32 fuel = 3;</code>
     */
    public int getFuel() {
      return fuel_;
    }

    public static final int CARGO_FIELD_NUMBER = 4;
    private int cargo_;
    /**
     * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
     */
    public int getCargoValue() {
      return cargo_;
    }
    /**
     * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
     */
    public CargoType getCargo() {
      CargoType result = CargoType.valueOf(cargo_);
      return result == null ? CargoType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getModelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, model_);
      }
      if (!getCaptainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, captain_);
      }
      if (fuel_ != 0) {
        output.writeInt32(3, fuel_);
      }
      if (cargo_ != CargoType.FRUIT.getNumber()) {
        output.writeEnum(4, cargo_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getModelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, model_);
      }
      if (!getCaptainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, captain_);
      }
      if (fuel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fuel_);
      }
      if (cargo_ != CargoType.FRUIT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, cargo_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SpaceShip)) {
        return super.equals(obj);
      }
      SpaceShip other = (SpaceShip) obj;

      boolean result = true;
      result = result && getModel()
          .equals(other.getModel());
      result = result && getCaptain()
          .equals(other.getCaptain());
      result = result && (getFuel()
          == other.getFuel());
      result = result && cargo_ == other.cargo_;
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + MODEL_FIELD_NUMBER;
      hash = (53 * hash) + getModel().hashCode();
      hash = (37 * hash) + CAPTAIN_FIELD_NUMBER;
      hash = (53 * hash) + getCaptain().hashCode();
      hash = (37 * hash) + FUEL_FIELD_NUMBER;
      hash = (53 * hash) + getFuel();
      hash = (37 * hash) + CARGO_FIELD_NUMBER;
      hash = (53 * hash) + cargo_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SpaceShip parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpaceShip parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpaceShip parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SpaceShip parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SpaceShip parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SpaceShip parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static SpaceShip parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static SpaceShip parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SpaceShip parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SpaceShip parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SpaceShip prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.example.demo.api.SpaceShip}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.example.demo.api.SpaceShip)
        SpaceShipOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SpacShipProtos.internal_static_com_example_demo_api_SpaceShip_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SpacShipProtos.internal_static_com_example_demo_api_SpaceShip_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SpaceShip.class, Builder.class);
      }

      // Construct using com.example.demo.api.SpacShipProtos.SpaceShip.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        model_ = "";

        captain_ = "";

        fuel_ = 0;

        cargo_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SpacShipProtos.internal_static_com_example_demo_api_SpaceShip_descriptor;
      }

      public SpaceShip getDefaultInstanceForType() {
        return SpaceShip.getDefaultInstance();
      }

      public SpaceShip build() {
        SpaceShip result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SpaceShip buildPartial() {
        SpaceShip result = new SpaceShip(this);
        result.model_ = model_;
        result.captain_ = captain_;
        result.fuel_ = fuel_;
        result.cargo_ = cargo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SpaceShip) {
          return mergeFrom((SpaceShip)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SpaceShip other) {
        if (other == SpaceShip.getDefaultInstance()) return this;
        if (!other.getModel().isEmpty()) {
          model_ = other.model_;
          onChanged();
        }
        if (!other.getCaptain().isEmpty()) {
          captain_ = other.captain_;
          onChanged();
        }
        if (other.getFuel() != 0) {
          setFuel(other.getFuel());
        }
        if (other.cargo_ != 0) {
          setCargoValue(other.getCargoValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SpaceShip parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SpaceShip) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object model_ = "";
      /**
       * <code>optional string model = 1;</code>
       */
      public String getModel() {
        Object ref = model_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string model = 1;</code>
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string model = 1;</code>
       */
      public Builder setModel(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        model_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 1;</code>
       */
      public Builder clearModel() {
        
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 1;</code>
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        model_ = value;
        onChanged();
        return this;
      }

      private Object captain_ = "";
      /**
       * <code>optional string captain = 2;</code>
       */
      public String getCaptain() {
        Object ref = captain_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          captain_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string captain = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCaptainBytes() {
        Object ref = captain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          captain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string captain = 2;</code>
       */
      public Builder setCaptain(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        captain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string captain = 2;</code>
       */
      public Builder clearCaptain() {
        
        captain_ = getDefaultInstance().getCaptain();
        onChanged();
        return this;
      }
      /**
       * <code>optional string captain = 2;</code>
       */
      public Builder setCaptainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        captain_ = value;
        onChanged();
        return this;
      }

      private int fuel_ ;
      /**
       * <code>optional int32 fuel = 3;</code>
       */
      public int getFuel() {
        return fuel_;
      }
      /**
       * <code>optional int32 fuel = 3;</code>
       */
      public Builder setFuel(int value) {
        
        fuel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fuel = 3;</code>
       */
      public Builder clearFuel() {
        
        fuel_ = 0;
        onChanged();
        return this;
      }

      private int cargo_ = 0;
      /**
       * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
       */
      public int getCargoValue() {
        return cargo_;
      }
      /**
       * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
       */
      public Builder setCargoValue(int value) {
        cargo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
       */
      public CargoType getCargo() {
        CargoType result = CargoType.valueOf(cargo_);
        return result == null ? CargoType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
       */
      public Builder setCargo(CargoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cargo_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.example.demo.api.SpaceShip.CargoType cargo = 4;</code>
       */
      public Builder clearCargo() {
        
        cargo_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.example.demo.api.SpaceShip)
    }

    // @@protoc_insertion_point(class_scope:com.example.demo.api.SpaceShip)
    private static final SpaceShip DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SpaceShip();
    }

    public static SpaceShip getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpaceShip>
        PARSER = new com.google.protobuf.AbstractParser<SpaceShip>() {
      public SpaceShip parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SpaceShip(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpaceShip> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SpaceShip> getParserForType() {
      return PARSER;
    }

    public SpaceShip getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_demo_api_SpaceShip_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_demo_api_SpaceShip_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017SpaceShip.proto\022\024com.example.demo.api\"" +
      "\230\001\n\tSpaceShip\022\r\n\005model\030\001 \001(\t\022\017\n\007captain\030" +
      "\002 \001(\t\022\014\n\004fuel\030\003 \001(\005\0228\n\005cargo\030\004 \001(\0162).com" +
      ".example.demo.api.SpaceShip.CargoType\"#\n" +
      "\tCargoType\022\t\n\005FRUIT\020\000\022\013\n\007WEAPONS\020\001B&\n\024co" +
      "m.example.demo.apiB\016SpacShipProtosb\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_example_demo_api_SpaceShip_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_demo_api_SpaceShip_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_demo_api_SpaceShip_descriptor,
        new String[] { "Model", "Captain", "Fuel", "Cargo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
